[project]
name = "nerve-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "python-socketio",
    "uvicorn",
    "langchain>=1.4.0",
    "langchain-openrouter",
    "langchain-groq",
    "langchain-anthropic",
    "langchain-baseten",
    "langchain-deepseek",
    "langgraph",
    "openai>=3.14.0",
    "httpx",
    "exa-py",
    "pydantic",
    "oci",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "black",
    "bandit",
]

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
ignore = ["N802"]

[tool.black]
line-length = 100
target-version = ["py313"]

[tool.bandit]
exclude_dirs = ["tests", ".venv"]
