MAX_MODEL_ATTEMPTS = 3
DEFAULT_RETRY_AFTER_SECONDS = 10
MAX_GIVE_UP_BOUNCES = 2
ERROR_COOLDOWN_SECONDS = 15
MODEL_CALL_TIMEOUT_SECONDS = 60
AGENT_TURN_TIMEOUT_SECONDS = 600
SUBAGENT_TIMEOUT_SECONDS = 120
TOOL_TIMEOUT_SECONDS = 30
COMMAND_TIMEOUT_SECONDS = 30
DEFAULT_READ_LIMIT = 500
WEB_FETCH_TIMEOUT_SECONDS = 15
WEB_FETCH_MAX_BYTES = 200000

# Inbound abuse protection for the public gateway (per client IP).
RATE_LIMIT_CONNECT_MAX = 30
RATE_LIMIT_CONNECT_WINDOW_SECONDS = 60
RATE_LIMIT_PROMPT_MAX = 10
RATE_LIMIT_PROMPT_WINDOW_SECONDS = 60
